# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-0613:
    model_name: gpt-4-0613
    endpoints: null
    api_type: openai
    parallel: 50

gpt-4-0125-preview:
    model_name: gpt-4-0125-preview
    endpoints: null
    api_type: openai
    parallel: 50

gpt-4o:
    model_name: gpt-4o
    endpoints: null
    api_type: openai
    parallel: 250

gpt-4o-mini:
    model_name: gpt-4o-mini
    endpoints: null
    api_type: openai
    parallel: 250

deepvk-russol-7b-sft:
    model_name: deepvk/russol-7b-sft
    endpoints:
        - api_base: http://ml4-6:8880/v1
          api_key: default-token
    api_type: openai
    parallel: 1

yandexgpt-pro-28-05-24:
    model_name: yandexgpt
    system_prompt: "Ты полезный AI-ассистент."
    endpoints: null
    api_type: yandex
    parallel: 1

yandexgpt-lite-08-05-24:
    model_name: yandexgpt-lite
    system_prompt: "Ты полезный AI-ассистент."
    endpoints: null
    api_type: yandex
    parallel: 1

GigaChat-25-07-24:
    model_name: GigaChat
    system_prompt: "Ты полезный AI-ассистент."
    endpoints: null
    api_type: sber
    parallel: 10

GigaChat-Pro-13-05-24:
    model_name: GigaChat-Pro
    system_prompt: "Ты полезный AI-ассистент."
    endpoints: null
    api_type: sber
    parallel: 10