# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-0613:
    model_name: gpt-4-0613
    endpoints: null
    api_type: openai
    parallel: 50

gpt-4-0125-preview:
    model_name: gpt-4-0125-preview
    endpoints: null
    api_type: openai
    parallel: 50

gpt-4o:
    model_name: gpt-4o
    endpoints: null
    api_type: openai
    parallel: 250

gpt-4o-mini:
    model_name: gpt-4o-mini
    endpoints: null
    api_type: openai
    parallel: 250

deepvk-russol-7b-sft:
    model_name: deepvk/russol-7b-sft
    endpoints:
          api_base: http://ml4-6:8880/v1
          api_key: default-token
    api_type: openai
    parallel: 1
