name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 1248
num_choices: 1

question_file: "question_ru.jsonl"

# a list of model to generate answers
model_list:
   - gpt-4-0613
   - deepvk-russol-7b-sft
